//------------------------------------------------------------------------
// Copyright(c) 2022 Steinberg Media Technologies GmbH.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"HelloWorld.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"HelloWorld VST3 (64Bit)"
#else
#define stringFileDescription	"HelloWorld VST3"
#endif
#define stringCompanyName		"Steinberg Media Technologies GmbH\0"
#define stringLegalCopyright	"Copyright(c) 2022 Steinberg Media Technologies GmbH."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
